eureka:
  instance:
    preferIpAddress: ${PREFER_IP_ADDRESS:true}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:frontend}
  resources:
    static-locations: file:${STATIC_LOCATIONS:/files}

server:
  port: ${PORT:80}
